import Header from "@/components/header";
import "./globals.css";
import Footer from "@/components/footer";
import AnimateRoot from "@/components/functions/animations/animations";

export const metadata = {
  title: "Boilerplate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AnimateRoot />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}